//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.06 at 03:15:09 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mphrx.com/soapapitut/PatientXSDPojo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mphrx.soapapitut.patientxsdpojo;
